// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gossip/message.proto
// </auto-generated>
// Original file comments:
// Copyright IBM Corp. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Gossip {
  /// <summary>
  /// Gossip
  /// </summary>
  public static partial class Gossip
  {
    static readonly string __ServiceName = "gossip.Gossip";

    static readonly grpc::Marshaller<global::Gossip.Envelope> __Marshaller_gossip_Envelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Gossip.Envelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Gossip.Empty> __Marshaller_gossip_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Gossip.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Gossip.Envelope, global::Gossip.Envelope> __Method_GossipStream = new grpc::Method<global::Gossip.Envelope, global::Gossip.Envelope>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GossipStream",
        __Marshaller_gossip_Envelope,
        __Marshaller_gossip_Envelope);

    static readonly grpc::Method<global::Gossip.Empty, global::Gossip.Empty> __Method_Ping = new grpc::Method<global::Gossip.Empty, global::Gossip.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_gossip_Empty,
        __Marshaller_gossip_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Gossip.MessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Gossip</summary>
    public abstract partial class GossipBase
    {
      /// <summary>
      /// GossipStream is the gRPC stream used for sending and receiving messages
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GossipStream(grpc::IAsyncStreamReader<global::Gossip.Envelope> requestStream, grpc::IServerStreamWriter<global::Gossip.Envelope> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Ping is used to probe a remote peer's aliveness
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Gossip.Empty> Ping(global::Gossip.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Gossip</summary>
    public partial class GossipClient : grpc::ClientBase<GossipClient>
    {
      /// <summary>Creates a new client for Gossip</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GossipClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Gossip that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GossipClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GossipClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GossipClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// GossipStream is the gRPC stream used for sending and receiving messages
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncDuplexStreamingCall<global::Gossip.Envelope, global::Gossip.Envelope> GossipStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GossipStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GossipStream is the gRPC stream used for sending and receiving messages
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncDuplexStreamingCall<global::Gossip.Envelope, global::Gossip.Envelope> GossipStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GossipStream, null, options);
      }
      /// <summary>
      /// Ping is used to probe a remote peer's aliveness
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Gossip.Empty Ping(global::Gossip.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Ping is used to probe a remote peer's aliveness
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Gossip.Empty Ping(global::Gossip.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>
      /// Ping is used to probe a remote peer's aliveness
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Gossip.Empty> PingAsync(global::Gossip.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Ping is used to probe a remote peer's aliveness
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Gossip.Empty> PingAsync(global::Gossip.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GossipClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GossipClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GossipBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GossipStream, serviceImpl.GossipStream)
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GossipBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GossipStream, serviceImpl.GossipStream);
      serviceBinder.AddMethod(__Method_Ping, serviceImpl.Ping);
    }

  }
}
#endregion
