// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: peer/transaction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from peer/transaction.proto</summary>
  public static partial class TransactionReflection {

    #region Descriptor
    /// <summary>File descriptor for peer/transaction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransactionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwZWVyL3RyYW5zYWN0aW9uLnByb3RvEgZwcm90b3MaH2dvb2dsZS9wcm90",
            "b2J1Zi90aW1lc3RhbXAucHJvdG8aHHBlZXIvcHJvcG9zYWxfcmVzcG9uc2Uu",
            "cHJvdG8aE2NvbW1vbi9jb21tb24ucHJvdG8iQQoRU2lnbmVkVHJhbnNhY3Rp",
            "b24SGQoRdHJhbnNhY3Rpb25fYnl0ZXMYASABKAwSEQoJc2lnbmF0dXJlGAIg",
            "ASgMIl0KFFByb2Nlc3NlZFRyYW5zYWN0aW9uEi0KE3RyYW5zYWN0aW9uRW52",
            "ZWxvcGUYASABKAsyEC5jb21tb24uRW52ZWxvcGUSFgoOdmFsaWRhdGlvbkNv",
            "ZGUYAiABKAUiOQoLVHJhbnNhY3Rpb24SKgoHYWN0aW9ucxgBIAMoCzIZLnBy",
            "b3Rvcy5UcmFuc2FjdGlvbkFjdGlvbiI0ChFUcmFuc2FjdGlvbkFjdGlvbhIO",
            "CgZoZWFkZXIYASABKAwSDwoHcGF5bG9hZBgCIAEoDCJtChZDaGFpbmNvZGVB",
            "Y3Rpb25QYXlsb2FkEiIKGmNoYWluY29kZV9wcm9wb3NhbF9wYXlsb2FkGAEg",
            "ASgMEi8KBmFjdGlvbhgCIAEoCzIfLnByb3Rvcy5DaGFpbmNvZGVFbmRvcnNl",
            "ZEFjdGlvbiJnChdDaGFpbmNvZGVFbmRvcnNlZEFjdGlvbhIhChlwcm9wb3Nh",
            "bF9yZXNwb25zZV9wYXlsb2FkGAEgASgMEikKDGVuZG9yc2VtZW50cxgCIAMo",
            "CzITLnByb3Rvcy5FbmRvcnNlbWVudCqUBQoQVHhWYWxpZGF0aW9uQ29kZRIJ",
            "CgVWQUxJRBAAEhAKDE5JTF9FTlZFTE9QRRABEg8KC0JBRF9QQVlMT0FEEAIS",
            "FQoRQkFEX0NPTU1PTl9IRUFERVIQAxIZChVCQURfQ1JFQVRPUl9TSUdOQVRV",
            "UkUQBBIgChxJTlZBTElEX0VORE9SU0VSX1RSQU5TQUNUSU9OEAUSHgoaSU5W",
            "QUxJRF9DT05GSUdfVFJBTlNBQ1RJT04QBhIaChZVTlNVUFBPUlRFRF9UWF9Q",
            "QVlMT0FEEAcSFQoRQkFEX1BST1BPU0FMX1RYSUQQCBISCg5EVVBMSUNBVEVf",
            "VFhJRBAJEh4KGkVORE9SU0VNRU5UX1BPTElDWV9GQUlMVVJFEAoSFgoSTVZD",
            "Q19SRUFEX0NPTkZMSUNUEAsSGQoVUEhBTlRPTV9SRUFEX0NPTkZMSUNUEAwS",
            "EwoPVU5LTk9XTl9UWF9UWVBFEA0SGgoWVEFSR0VUX0NIQUlOX05PVF9GT1VO",
            "RBAOEhQKEE1BUlNIQUxfVFhfRVJST1IQDxIQCgxOSUxfVFhBQ1RJT04QEBIV",
            "ChFFWFBJUkVEX0NIQUlOQ09ERRAREh4KGkNIQUlOQ09ERV9WRVJTSU9OX0NP",
            "TkZMSUNUEBISGAoUQkFEX0hFQURFUl9FWFRFTlNJT04QExIWChJCQURfQ0hB",
            "Tk5FTF9IRUFERVIQFBIYChRCQURfUkVTUE9OU0VfUEFZTE9BRBAVEg0KCUJB",
            "RF9SV1NFVBAWEhQKEElMTEVHQUxfV1JJVEVTRVQQFxIUChBJTlZBTElEX1dS",
            "SVRFU0VUEBgSEgoNTk9UX1ZBTElEQVRFRBD+ARIZChRJTlZBTElEX09USEVS",
            "X1JFQVNPThD/ASooCgxNZXRhRGF0YUtleXMSGAoUVkFMSURBVElPTl9QQVJB",
            "TUVURVIQAEJjCiJvcmcuaHlwZXJsZWRnZXIuZmFicmljLnByb3Rvcy5wZWVy",
            "QhJUcmFuc2FjdGlvblBhY2thZ2VaKWdpdGh1Yi5jb20vaHlwZXJsZWRnZXIv",
            "ZmFicmljL3Byb3Rvcy9wZWVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Protos.ProposalResponseReflection.Descriptor, global::Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protos.TxValidationCode), typeof(global::Protos.MetaDataKeys), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.SignedTransaction), global::Protos.SignedTransaction.Parser, new[]{ "TransactionBytes", "Signature" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ProcessedTransaction), global::Protos.ProcessedTransaction.Parser, new[]{ "TransactionEnvelope", "ValidationCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.Transaction), global::Protos.Transaction.Parser, new[]{ "Actions" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.TransactionAction), global::Protos.TransactionAction.Parser, new[]{ "Header", "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ChaincodeActionPayload), global::Protos.ChaincodeActionPayload.Parser, new[]{ "ChaincodeProposalPayload", "Action" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ChaincodeEndorsedAction), global::Protos.ChaincodeEndorsedAction.Parser, new[]{ "ProposalResponsePayload", "Endorsements" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TxValidationCode {
    [pbr::OriginalName("VALID")] Valid = 0,
    [pbr::OriginalName("NIL_ENVELOPE")] NilEnvelope = 1,
    [pbr::OriginalName("BAD_PAYLOAD")] BadPayload = 2,
    [pbr::OriginalName("BAD_COMMON_HEADER")] BadCommonHeader = 3,
    [pbr::OriginalName("BAD_CREATOR_SIGNATURE")] BadCreatorSignature = 4,
    [pbr::OriginalName("INVALID_ENDORSER_TRANSACTION")] InvalidEndorserTransaction = 5,
    [pbr::OriginalName("INVALID_CONFIG_TRANSACTION")] InvalidConfigTransaction = 6,
    [pbr::OriginalName("UNSUPPORTED_TX_PAYLOAD")] UnsupportedTxPayload = 7,
    [pbr::OriginalName("BAD_PROPOSAL_TXID")] BadProposalTxid = 8,
    [pbr::OriginalName("DUPLICATE_TXID")] DuplicateTxid = 9,
    [pbr::OriginalName("ENDORSEMENT_POLICY_FAILURE")] EndorsementPolicyFailure = 10,
    [pbr::OriginalName("MVCC_READ_CONFLICT")] MvccReadConflict = 11,
    [pbr::OriginalName("PHANTOM_READ_CONFLICT")] PhantomReadConflict = 12,
    [pbr::OriginalName("UNKNOWN_TX_TYPE")] UnknownTxType = 13,
    [pbr::OriginalName("TARGET_CHAIN_NOT_FOUND")] TargetChainNotFound = 14,
    [pbr::OriginalName("MARSHAL_TX_ERROR")] MarshalTxError = 15,
    [pbr::OriginalName("NIL_TXACTION")] NilTxaction = 16,
    [pbr::OriginalName("EXPIRED_CHAINCODE")] ExpiredChaincode = 17,
    [pbr::OriginalName("CHAINCODE_VERSION_CONFLICT")] ChaincodeVersionConflict = 18,
    [pbr::OriginalName("BAD_HEADER_EXTENSION")] BadHeaderExtension = 19,
    [pbr::OriginalName("BAD_CHANNEL_HEADER")] BadChannelHeader = 20,
    [pbr::OriginalName("BAD_RESPONSE_PAYLOAD")] BadResponsePayload = 21,
    [pbr::OriginalName("BAD_RWSET")] BadRwset = 22,
    [pbr::OriginalName("ILLEGAL_WRITESET")] IllegalWriteset = 23,
    [pbr::OriginalName("INVALID_WRITESET")] InvalidWriteset = 24,
    [pbr::OriginalName("NOT_VALIDATED")] NotValidated = 254,
    [pbr::OriginalName("INVALID_OTHER_REASON")] InvalidOtherReason = 255,
  }

  /// <summary>
  /// Reserved entries in the key-level metadata map
  /// </summary>
  public enum MetaDataKeys {
    [pbr::OriginalName("VALIDATION_PARAMETER")] ValidationParameter = 0,
  }

  #endregion

  #region Messages
  /// <summary>
  /// This message is necessary to facilitate the verification of the signature
  /// (in the signature field) over the bytes of the transaction (in the
  /// transactionBytes field).
  /// </summary>
  public sealed partial class SignedTransaction : pb::IMessage<SignedTransaction> {
    private static readonly pb::MessageParser<SignedTransaction> _parser = new pb::MessageParser<SignedTransaction>(() => new SignedTransaction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignedTransaction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.TransactionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignedTransaction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignedTransaction(SignedTransaction other) : this() {
      transactionBytes_ = other.transactionBytes_;
      signature_ = other.signature_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignedTransaction Clone() {
      return new SignedTransaction(this);
    }

    /// <summary>Field number for the "transaction_bytes" field.</summary>
    public const int TransactionBytesFieldNumber = 1;
    private pb::ByteString transactionBytes_ = pb::ByteString.Empty;
    /// <summary>
    /// The bytes of the Transaction. NDD
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString TransactionBytes {
      get { return transactionBytes_; }
      set {
        transactionBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 2;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    /// <summary>
    /// Signature of the transactionBytes The public key of the signature is in
    /// the header field of TransactionAction There might be multiple
    /// TransactionAction, so multiple headers, but there should be same
    /// transactor identity (cert) in all headers
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignedTransaction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignedTransaction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TransactionBytes != other.TransactionBytes) return false;
      if (Signature != other.Signature) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TransactionBytes.Length != 0) hash ^= TransactionBytes.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TransactionBytes.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(TransactionBytes);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TransactionBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TransactionBytes);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignedTransaction other) {
      if (other == null) {
        return;
      }
      if (other.TransactionBytes.Length != 0) {
        TransactionBytes = other.TransactionBytes;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TransactionBytes = input.ReadBytes();
            break;
          }
          case 18: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// ProcessedTransaction wraps an Envelope that includes a transaction along with an indication
  /// of whether the transaction was validated or invalidated by committing peer.
  /// The use case is that GetTransactionByID API needs to retrieve the transaction Envelope
  /// from block storage, and return it to a client, and indicate whether the transaction
  /// was validated or invalidated by committing peer. So that the originally submitted
  /// transaction Envelope is not modified, the ProcessedTransaction wrapper is returned.
  /// </summary>
  public sealed partial class ProcessedTransaction : pb::IMessage<ProcessedTransaction> {
    private static readonly pb::MessageParser<ProcessedTransaction> _parser = new pb::MessageParser<ProcessedTransaction>(() => new ProcessedTransaction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProcessedTransaction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.TransactionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProcessedTransaction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProcessedTransaction(ProcessedTransaction other) : this() {
      transactionEnvelope_ = other.transactionEnvelope_ != null ? other.transactionEnvelope_.Clone() : null;
      validationCode_ = other.validationCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProcessedTransaction Clone() {
      return new ProcessedTransaction(this);
    }

    /// <summary>Field number for the "transactionEnvelope" field.</summary>
    public const int TransactionEnvelopeFieldNumber = 1;
    private global::Common.Envelope transactionEnvelope_;
    /// <summary>
    /// An Envelope which includes a processed transaction
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Envelope TransactionEnvelope {
      get { return transactionEnvelope_; }
      set {
        transactionEnvelope_ = value;
      }
    }

    /// <summary>Field number for the "validationCode" field.</summary>
    public const int ValidationCodeFieldNumber = 2;
    private int validationCode_;
    /// <summary>
    /// An indication of whether the transaction was validated or invalidated by committing peer
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValidationCode {
      get { return validationCode_; }
      set {
        validationCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProcessedTransaction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProcessedTransaction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TransactionEnvelope, other.TransactionEnvelope)) return false;
      if (ValidationCode != other.ValidationCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (transactionEnvelope_ != null) hash ^= TransactionEnvelope.GetHashCode();
      if (ValidationCode != 0) hash ^= ValidationCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (transactionEnvelope_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TransactionEnvelope);
      }
      if (ValidationCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ValidationCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (transactionEnvelope_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransactionEnvelope);
      }
      if (ValidationCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValidationCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProcessedTransaction other) {
      if (other == null) {
        return;
      }
      if (other.transactionEnvelope_ != null) {
        if (transactionEnvelope_ == null) {
          transactionEnvelope_ = new global::Common.Envelope();
        }
        TransactionEnvelope.MergeFrom(other.TransactionEnvelope);
      }
      if (other.ValidationCode != 0) {
        ValidationCode = other.ValidationCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (transactionEnvelope_ == null) {
              transactionEnvelope_ = new global::Common.Envelope();
            }
            input.ReadMessage(transactionEnvelope_);
            break;
          }
          case 16: {
            ValidationCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The transaction to be sent to the ordering service. A transaction contains
  /// one or more TransactionAction. Each TransactionAction binds a proposal to
  /// potentially multiple actions. The transaction is atomic meaning that either
  /// all actions in the transaction will be committed or none will.  Note that
  /// while a Transaction might include more than one Header, the Header.creator
  /// field must be the same in each.
  /// A single client is free to issue a number of independent Proposal, each with
  /// their header (Header) and request payload (ChaincodeProposalPayload).  Each
  /// proposal is independently endorsed generating an action
  /// (ProposalResponsePayload) with one signature per Endorser. Any number of
  /// independent proposals (and their action) might be included in a transaction
  /// to ensure that they are treated atomically.
  /// </summary>
  public sealed partial class Transaction : pb::IMessage<Transaction> {
    private static readonly pb::MessageParser<Transaction> _parser = new pb::MessageParser<Transaction>(() => new Transaction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Transaction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.TransactionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transaction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transaction(Transaction other) : this() {
      actions_ = other.actions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transaction Clone() {
      return new Transaction(this);
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Protos.TransactionAction> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(10, global::Protos.TransactionAction.Parser);
    private readonly pbc::RepeatedField<global::Protos.TransactionAction> actions_ = new pbc::RepeatedField<global::Protos.TransactionAction>();
    /// <summary>
    /// The payload is an array of TransactionAction. An array is necessary to
    /// accommodate multiple actions per transaction
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Protos.TransactionAction> Actions {
      get { return actions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Transaction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Transaction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!actions_.Equals(other.actions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= actions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      actions_.WriteTo(output, _repeated_actions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += actions_.CalculateSize(_repeated_actions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Transaction other) {
      if (other == null) {
        return;
      }
      actions_.Add(other.actions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// TransactionAction binds a proposal to its action.  The type field in the
  /// header dictates the type of action to be applied to the ledger.
  /// </summary>
  public sealed partial class TransactionAction : pb::IMessage<TransactionAction> {
    private static readonly pb::MessageParser<TransactionAction> _parser = new pb::MessageParser<TransactionAction>(() => new TransactionAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransactionAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.TransactionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionAction(TransactionAction other) : this() {
      header_ = other.header_;
      payload_ = other.payload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionAction Clone() {
      return new TransactionAction(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private pb::ByteString header_ = pb::ByteString.Empty;
    /// <summary>
    /// The header of the proposal action, which is the proposal header
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Header {
      get { return header_; }
      set {
        header_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    /// <summary>
    /// The payload of the action as defined by the type in the header For
    /// chaincode, it's the bytes of ChaincodeActionPayload
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransactionAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransactionAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Header != other.Header) return false;
      if (Payload != other.Payload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Header.Length != 0) hash ^= Header.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Header.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Header);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Header.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Header);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransactionAction other) {
      if (other == null) {
        return;
      }
      if (other.Header.Length != 0) {
        Header = other.Header;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Header = input.ReadBytes();
            break;
          }
          case 18: {
            Payload = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// ChaincodeActionPayload is the message to be used for the TransactionAction's
  /// payload when the Header's type is set to CHAINCODE.  It carries the
  /// chaincodeProposalPayload and an endorsed action to apply to the ledger.
  /// </summary>
  public sealed partial class ChaincodeActionPayload : pb::IMessage<ChaincodeActionPayload> {
    private static readonly pb::MessageParser<ChaincodeActionPayload> _parser = new pb::MessageParser<ChaincodeActionPayload>(() => new ChaincodeActionPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChaincodeActionPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.TransactionReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeActionPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeActionPayload(ChaincodeActionPayload other) : this() {
      chaincodeProposalPayload_ = other.chaincodeProposalPayload_;
      action_ = other.action_ != null ? other.action_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeActionPayload Clone() {
      return new ChaincodeActionPayload(this);
    }

    /// <summary>Field number for the "chaincode_proposal_payload" field.</summary>
    public const int ChaincodeProposalPayloadFieldNumber = 1;
    private pb::ByteString chaincodeProposalPayload_ = pb::ByteString.Empty;
    /// <summary>
    /// This field contains the bytes of the ChaincodeProposalPayload message from
    /// the original invocation (essentially the arguments) after the application
    /// of the visibility function. The main visibility modes are "full" (the
    /// entire ChaincodeProposalPayload message is included here), "hash" (only
    /// the hash of the ChaincodeProposalPayload message is included) or
    /// "nothing".  This field will be used to check the consistency of
    /// ProposalResponsePayload.proposalHash.  For the CHAINCODE type,
    /// ProposalResponsePayload.proposalHash is supposed to be H(ProposalHeader ||
    /// f(ChaincodeProposalPayload)) where f is the visibility function.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ChaincodeProposalPayload {
      get { return chaincodeProposalPayload_; }
      set {
        chaincodeProposalPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 2;
    private global::Protos.ChaincodeEndorsedAction action_;
    /// <summary>
    /// The list of actions to apply to the ledger
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.ChaincodeEndorsedAction Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChaincodeActionPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChaincodeActionPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChaincodeProposalPayload != other.ChaincodeProposalPayload) return false;
      if (!object.Equals(Action, other.Action)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChaincodeProposalPayload.Length != 0) hash ^= ChaincodeProposalPayload.GetHashCode();
      if (action_ != null) hash ^= Action.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ChaincodeProposalPayload.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ChaincodeProposalPayload);
      }
      if (action_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChaincodeProposalPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ChaincodeProposalPayload);
      }
      if (action_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Action);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChaincodeActionPayload other) {
      if (other == null) {
        return;
      }
      if (other.ChaincodeProposalPayload.Length != 0) {
        ChaincodeProposalPayload = other.ChaincodeProposalPayload;
      }
      if (other.action_ != null) {
        if (action_ == null) {
          action_ = new global::Protos.ChaincodeEndorsedAction();
        }
        Action.MergeFrom(other.Action);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ChaincodeProposalPayload = input.ReadBytes();
            break;
          }
          case 18: {
            if (action_ == null) {
              action_ = new global::Protos.ChaincodeEndorsedAction();
            }
            input.ReadMessage(action_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// ChaincodeEndorsedAction carries information about the endorsement of a
  /// specific proposal
  /// </summary>
  public sealed partial class ChaincodeEndorsedAction : pb::IMessage<ChaincodeEndorsedAction> {
    private static readonly pb::MessageParser<ChaincodeEndorsedAction> _parser = new pb::MessageParser<ChaincodeEndorsedAction>(() => new ChaincodeEndorsedAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChaincodeEndorsedAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.TransactionReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeEndorsedAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeEndorsedAction(ChaincodeEndorsedAction other) : this() {
      proposalResponsePayload_ = other.proposalResponsePayload_;
      endorsements_ = other.endorsements_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChaincodeEndorsedAction Clone() {
      return new ChaincodeEndorsedAction(this);
    }

    /// <summary>Field number for the "proposal_response_payload" field.</summary>
    public const int ProposalResponsePayloadFieldNumber = 1;
    private pb::ByteString proposalResponsePayload_ = pb::ByteString.Empty;
    /// <summary>
    /// This is the bytes of the ProposalResponsePayload message signed by the
    /// endorsers.  Recall that for the CHAINCODE type, the
    /// ProposalResponsePayload's extenstion field carries a ChaincodeAction
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ProposalResponsePayload {
      get { return proposalResponsePayload_; }
      set {
        proposalResponsePayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endorsements" field.</summary>
    public const int EndorsementsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Protos.Endorsement> _repeated_endorsements_codec
        = pb::FieldCodec.ForMessage(18, global::Protos.Endorsement.Parser);
    private readonly pbc::RepeatedField<global::Protos.Endorsement> endorsements_ = new pbc::RepeatedField<global::Protos.Endorsement>();
    /// <summary>
    /// The endorsement of the proposal, basically the endorser's signature over
    /// proposalResponsePayload
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Protos.Endorsement> Endorsements {
      get { return endorsements_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChaincodeEndorsedAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChaincodeEndorsedAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProposalResponsePayload != other.ProposalResponsePayload) return false;
      if(!endorsements_.Equals(other.endorsements_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ProposalResponsePayload.Length != 0) hash ^= ProposalResponsePayload.GetHashCode();
      hash ^= endorsements_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ProposalResponsePayload.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ProposalResponsePayload);
      }
      endorsements_.WriteTo(output, _repeated_endorsements_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ProposalResponsePayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProposalResponsePayload);
      }
      size += endorsements_.CalculateSize(_repeated_endorsements_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChaincodeEndorsedAction other) {
      if (other == null) {
        return;
      }
      if (other.ProposalResponsePayload.Length != 0) {
        ProposalResponsePayload = other.ProposalResponsePayload;
      }
      endorsements_.Add(other.endorsements_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ProposalResponsePayload = input.ReadBytes();
            break;
          }
          case 18: {
            endorsements_.AddEntriesFrom(input, _repeated_endorsements_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
